chore(redux setup): redux setup
atlp-rwanda/e-comm-team-techtitans-fn pull request #10
Opened 2023-05-19 22:45 UTC by Gentille-dev

2023-05-20 10:19 UTC, Folio123-c approved these changes

2023-05-20 11:29 UTC, madebypatrick approved these changes

2023-05-20 11:58 UTC, Virgile1k approved these changes
Checked

2023-05-20 12:03 UTC, Rod-code approved these changes

2023-05-20 13:31 UTC, Cynthia-kam approved these changes

2023-05-21 12:38 UTC, EdwinBayingana requested changes
Please set up **redux-toolkit** instead of **redux**, since we agreed on this a team.

2023-05-21 12:44 UTC, EdwinBayingana approved these changes

2023-05-22 14:19 UTC, merged