#185188993Users should be able Signup/Register to the E-commerce App and verify email
atlp-rwanda/e-comm-team-techtitans-fn pull request #14
Opened 2023-05-23 07:21 UTC by Virgile1k

#what does this pr do ?
 Users should be able Signup/Register to the E-commerce App and verify email

<img width="1440" alt="Screen Shot 2023-05-26 at 11 42 42" src="https://github.com/atlp-rwanda/e-comm-team-techtitans-fn/assets/97120342/a101cde7-caaa-464a-9ba1-0c7b47c9b3e7">

2023-05-26 13:37 UTC, NdatimanaSamuel approved these changes

2023-05-26 13:38 UTC, Gentille-dev approved these changes

2023-05-26 13:46 UTC, Rod-code approved these changes

2023-05-26 13:47 UTC, KAYITARES approved these changes

2023-05-26 13:53 UTC, EdwinBayingana approved these changes

2023-05-29 09:31 UTC, didasmbalanya requested changes
Looks okay, but please remove the comments and make the backend baseURl shared across rather than typing it everywhere

2023-05-29 09:31 UTC, didasmbalanya commented on src/components/features/SignupSlice.js
> +        "https://ecommerce-tech-titans.herokuapp.com/api/v1/user/signup",
Move the base backend URL to a util file so it can be exported to all other files. That way if we ever change our backend to a different URL we only have to update once

2023-05-29 09:31 UTC, didasmbalanya commented on src/components/features/SignupSlice.js
> +      console.log("Signup response", response.data);
remove console

2023-05-29 09:31 UTC, didasmbalanya commented on src/components/features/SignupSlice.js
> +      console.log("Signup error:", error.response.data.message);
remove console

2023-05-29 09:31 UTC, didasmbalanya commented on src/components/features/SignupSlice.js
> +        "https://ecommerce-tech-titans.herokuapp.com/api/v1/user/verifyEmail"
move base URL to a util file

2023-05-29 09:31 UTC, didasmbalanya commented on src/components/features/SignupSlice.js
> +      console.log("Verify email response", response.data);
remove

2023-05-30 13:32 UTC, merged